// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="nuxt-windicss" />
/// <reference types="@nuxt/image" />
/// <reference types="nuxt-graphql-request" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path=".nuxt/nitro.d.ts" />
/// <reference types="unplugin-vue2-script-setup/types" />
/// <reference path=".nuxt/auto-imports.d.ts" />
export {}
