fragment CustomerFragment on Customer {
  lastName
  email
  firstName
  username
  databaseId
  sessionToken
  isPayingCustomer
  billing {
    address1
    address2
    city
    country
    email
    firstName
    lastName
    phone
    postcode
    company
    state
  }
  shipping {
    address1
    address2
    city
    country
    email
    firstName
    lastName
    phone
    postcode
    company
    state
  }
}
