query getCategoryChildren($slug: String!) {
  productCategories(where: { slug: [$slug] }) {
    nodes {
      id
      name
      slug
      children(first: 50) {
        nodes {
          id
          name
          slug
          children(first: 50) {
            nodes {
              id
              name
              slug
            }
          }
        }
      }
    }
  }
}
