query getCategoryChildren($slug: ID!) {
  productCategory(id: $slug, idType: SLUG) {
    id
    name
    slug
    children {
      nodes {
        id
        name
        slug
        children {
          nodes {
            id
            name
            slug
          }
        }
      }
    }
  }
}
