query GetCategoryByUri($uri: String!) {
  productCategoryBy(uri: $uri) {
    id
    name
    slug
    uri
    parent {
      node {
        id
        name
        slug
        uri
        children(first: 100) {
          nodes {
            id
            name
            slug
            uri
          }
        }
      }
    }
    children(first: 100) {
      nodes {
        id
        name
        slug
        uri
      }
    }
  }
}
