query getCategoryContextById($id: ID!) {
  productCategory(id: $id, idType: ID) {
    id
    name
    slug
    parent {
      node {
        id
        name
        slug
        children(first: 100) {
          nodes {
            id
            name
            slug
          }
        }
      }
    }
    children(first: 100) {
      nodes {
        id
        name
        slug
      }
    }
  }
}
