query GetFooterMenus {
  footer1: menu(id: "footer-1", idType: SLUG) {
    name
    slug
    menuItems {
      nodes {
        id
        label
        url
      }
    }
  }
  footer2: menu(id: "footer-2", idType: SLUG) {
    name
    slug
    menuItems {
      nodes {
        id
        label
        url
      }
    }
  }
  footer3: menu(id: "footer-3", idType: SLUG) {
    name
    slug
    menuItems {
      nodes {
        id
        label
        url
      }
    }
  }
}
