query GetFooterMenus {
  menus {
    nodes {
      id
      databaseId
      name
      slug
      menuItems {
        nodes {
          id
          label
          url
        }
      }
    }
  }
}
