query GetFooterMenus {
  footer1: menuItems(where: { location: FOOTER_1 }) {
    nodes {
      id
      label
      url
    }
  }
  footer2: menuItems(where: { location: FOOTER_2 }) {
    nodes {
      id
      label
      url
    }
  }
  footer3: menuItems(where: { location: FOOTER_3 }) {
    nodes {
      id
      label
      url
    }
  }
}
