query GetProductsByCategory($slug: ID!, $first: Int = 24) {
  productCategory(id: $slug, idType: SLUG) {
    name
    slug
    products(first: $first) {
      nodes {
        id
        databaseId
        slug
        name
        price
        regularPrice
        salePrice
        stockStatus
        image {
          sourceUrl
          altText
        }
        productCategories {
          nodes {
            id
            name
            slug
          }
        }
        attributes {
          nodes {
            label
            options
          }
        }
      }
    }
  }
}
