query GetRelatedCategories($id: ID!, $idType: ProductCategoryIdType = URI) {
  productCategory(id: $id, idType: $idType) {
    id
    name
    slug
    uri
    parentId
    parent {
      node {
        id
        name
        slug
        uri
      }
    }
    children {
      nodes {
        id
        name
        slug
        uri
      }
    }
  }

  # optioneel: alle categorieën (voor siblings)
  productCategories(first: 100) {
    nodes {
      id
      name
      slug
      uri
      parentId
    }
  }
}
