query GetRelatedCategories($id: ID!, $idType: ProductCategoryIdType!) {
  productCategory(id: $id, idType: $idType) {
    id
    name
    uri
    slug
    parentId
    children {
      nodes {
        name
        slug
        uri
      }
    }
  }
  productCategories(first: 100) {
    nodes {
      name
      slug
      parentId
      uri
    }
  }
}
