query GetRelatedCategories($slug: ID!) {
  productCategory(id: $slug, idType: SLUG) {
    id
    name
    slug
    uri
    parent {
      node {
        id
        name
        slug
      }
    }
    children {
      nodes {
        id
        name
        slug
      }
    }
    parentId
  }
  productCategories(first: 100) {
    nodes {
      id
      name
      slug
      parentId
      uri
    }
  }
}
