<script lang="ts" setup>
import { ProductsOrderByEnum } from '#gql/default';

const { siteName, description, shortDescription, siteImage } = useAppConfig();
const [{ data }, { data: productData }] = await Promise.all([
  useAsyncGql('getProductCategories', { first: 6 }),
  useAsyncGql('getProducts', { first: 8, orderby: ProductsOrderByEnum.Popularity }),
]);
const categories = computed(() => data.value?.productCategories?.nodes || []);
const products = computed(() => productData.value?.products?.nodes || []);
useSeoMeta({ title: 'Plants for happier spaces', ogTitle: siteName, description, ogDescription: shortDescription, ogImage: siteImage, twitterCard: 'summary_large_image' });
</script>

<template>
  <main class="w-full overflow-hidden bg-[#fffefb] text-[#1a3b22]">
    <section class="container grid items-center gap-10 py-14 lg:min-h-145 lg:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)] lg:py-24">
      <div class="max-w-xl lg:pl-8"><p class="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#588354]"><span class="size-2 rounded-[50%_50%_50%_0] bg-[#6b9d58] -rotate-35" /> Natural · Fresh · Beautiful</p><h1 class="text-5xl font-bold leading-[.98] tracking-[-.075em] sm:text-6xl lg:text-8xl">Bring nature<br>to your <span class="text-[#5b984d]">life.</span></h1><p class="my-6 max-w-sm text-base leading-7 text-[#546356]">Find the perfect plants to refresh your home and brighten your everyday life.</p><div class="flex flex-wrap items-center gap-4"><NuxtLink to="/products" class="inline-flex items-center gap-7 rounded-full bg-[#3d7b3d] px-6 py-3.5 text-sm font-bold text-white">Shop plants <span class="text-xl">→</span></NuxtLink><NuxtLink to="/categories" class="inline-flex items-center gap-2 px-1 py-3 text-sm font-bold">Explore collections <span class="text-xl">→</span></NuxtLink></div></div>
      <div class="relative min-h-90 overflow-hidden rounded-[2rem] bg-[#f2f7ec] lg:min-h-120 lg:rounded-[42%_42%_30%_30%/30%_30%_18%_18%]"><NuxtImg src="/images/plant-hero.png" width="1672" height="941" alt="Lush houseplant in an ivory pot" preload class="absolute inset-0 size-full object-cover mix-blend-multiply" /><div class="absolute bottom-8 right-6 rounded-2xl bg-white/95 p-5 shadow-xl shadow-[#244423]/10"><b class="block text-3xl leading-none text-[#2f6934]">200+</b><span class="mt-1 block text-xs leading-4 text-[#667168]">Plants delivered<br>with love</span></div></div>
    </section>
    <section class="container grid grid-cols-1 gap-px rounded-2xl bg-[#286134] p-5 text-white sm:grid-cols-2 lg:grid-cols-4"><div class="flex items-center gap-3 border-b border-white/20 p-3 lg:border-r lg:border-b-0"><Icon name="ion:leaf-outline" size="27" /><span><b class="block text-sm">Fresh from growers</b><small class="text-xs text-[#dcebd7]">Healthy plants, carefully packed</small></span></div><div class="flex items-center gap-3 border-b border-white/20 p-3 lg:border-r lg:border-b-0"><Icon name="ion:book-outline" size="27" /><span><b class="block text-sm">Plant care support</b><small class="text-xs text-[#dcebd7]">Simple tips for every leaf</small></span></div><div class="flex items-center gap-3 border-b border-white/20 p-3 sm:border-b-0 lg:border-r"><Icon name="ion:shield-checkmark-outline" size="27" /><span><b class="block text-sm">Safe delivery</b><small class="text-xs text-[#dcebd7]">Securely delivered to your door</small></span></div><div class="flex items-center gap-3 p-3"><Icon name="ion:heart-outline" size="27" /><span><b class="block text-sm">Easy returns</b><small class="text-xs text-[#dcebd7]">30-day happiness promise</small></span></div></section>
    <section class="container mt-20"><div class="mb-8 flex items-end justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-wide text-[#588354]">Our favourites</p><h2 class="text-3xl font-bold tracking-[-.055em] sm:text-4xl">New arrivals</h2></div><NuxtLink to="/products" class="text-sm font-bold text-[#4c7d49]">View all <span class="ml-2 text-xl">→</span></NuxtLink></div><ProductRow v-if="products.length" :products="products" class="grid-cols-2 md:grid-cols-4" /></section>
    <section class="container mt-20"><div class="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#245429] to-[#3d7739] px-8 py-14 text-white sm:px-16"><div class="relative z-10 max-w-xl"><p class="mb-4 text-xs font-bold uppercase tracking-wide text-[#c8e1a5]">Limited time offer</p><h2 class="text-4xl font-bold leading-none tracking-[-.055em] sm:text-6xl">Get up to <span class="text-[#c9e99d]">30% off</span><br>on indoor plants</h2><p class="mt-5 max-w-md leading-7 text-[#e1ecdc]">Bring more happiness home with our hand-picked green companions.</p><NuxtLink to="/products" class="mt-7 inline-flex items-center gap-6 rounded-full border border-[#d1e7c7] px-5 py-3 text-sm font-bold">Explore collection <span class="text-xl">→</span></NuxtLink></div><Icon name="ion:leaf" class="absolute -bottom-20 right-2 text-[24rem] text-[#9bcf78]/20" /></div></section>
    <section v-if="categories.length" class="container mt-20 pb-20"><div class="mb-8 flex items-end justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-wide text-[#588354]">Find your match</p><h2 class="text-3xl font-bold tracking-[-.055em] sm:text-4xl">Shop by plant type</h2></div><NuxtLink to="/categories" class="text-sm font-bold text-[#4c7d49]">View all <span class="ml-2 text-xl">→</span></NuxtLink></div><div class="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6"><CategoryCard v-for="category in categories" :key="category.slug || category.databaseId" :node="category" /></div></section>
  </main>
</template>
