fragment SimpleProduct on SimpleProduct {
  price
  slug
  salePrice
  regularPrice
  stockStatus
  stockQuantity
  description
  averageRating
  reviewCount
  image {
    sourceUrl
    altText
    title
  }
}