query getCart {
  cart {
    total
    isEmpty
    contents {
      itemCount
      nodes {
        quantity
        key
        product {
          node {
            name
            slug
            sku
            databaseId
            type
            image {
              sourceUrl(size: SHOP_THUMBNAIL)
            }
            ... on VariableProduct {
              name
              price
            }
            ... on SimpleProduct {
              name
              price
            }
          }
        }
        variation{
          node{
            name
            price
            image{
              sourceUrl(size: SHOP_THUMBNAIL)
            }
          }
        }
      }
      productCount
    }
  }
  customer {
    lastName
    email
    firstName
    username
  }
  viewer{
    lastName
    email
    firstName
    username
  }
}
