query getCart {
  cart {
    total
    contents {
      nodes {
        product {
          node {
            ... on SimpleProduct {
              id
              name
              price
            }
          }
        }
        quantity
      }
      itemCount
    }
  }
  viewer{
    username
  }
}
