query getOrder($id: ID!) {
  order(id: $id, idType: DATABASE_ID) {
    paymentMethod
    status
    date
    databaseId
    subtotal
    total
    customer {
      email
    }
  }
  customer {
    orders {
      nodes {
        paymentMethod
        status
        date
        databaseId
        subtotal
        total
        customer {
          email
        }
      }
    }
  }
}