query getOrder($id: ID!) {
  order(id: $id, idType: DATABASE_ID) {
    needsPayment
    needsProcessing
    status
    databaseId
    orderKey
    subtotal
    total
    subtotal
    totalTax
    shippingTotal
    paymentMethodTitle
    paymentMethod
    date
    subtotal
    customer {
      email
    }
    lineItems {
      nodes {
        quantity
        total
        product {
          node {
            name
            image {
              sourceUrl(size: THUMBNAIL)
              altText
              title
            }
          }
        }
        variation {
          node {
            name
            image {
              sourceUrl(size: THUMBNAIL)
              altText
              title
            }
          }
        }
      }
    }
  }
  customer {
    ...CustomerFragment
  }
}
