query getCategories {
  productCategories( where: {orderby: COUNT, order: DESC, hideEmpty: true} ) {
    nodes {
      count
      databaseId
      id
      name
      slug
      image {
        sourceUrl
      }
    }
  }
}
