#import "~/gql/fragments/SimpleProduct.gql"
#import "~/gql/fragments/VariableProduct.gql"

query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    name
    databaseId
    attributes {
      nodes {
        variation
        name
        label
        options
      }
    }
    productCategories {
      nodes {
        databaseId
        slug
        name
        count
      }
    }
    slug
    ... SimpleProduct
    ... VariableProduct
    related(first: 5) {
      nodes {
        name
        ... SimpleProduct
        ... VariableProduct
      }
    }
  }
}