query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    name
    databaseId
    description
    image {
      sourceUrl
      altText
      title
    }
    attributes {
      nodes {
        variation
        name
        label
        options
      }
    }
    productCategories {
      nodes {
        databaseId
        slug
        name
        count
      }
    }
    averageRating
    reviewCount
    slug
    ... on SimpleProduct {
      price
      stockStatus
      stockQuantity
    }
    ... on VariableProduct {
      price
      stockStatus
      stockQuantity
      attributes {
        nodes {
          name
          options
          variation
          visible
        }
      }
      defaultAttributes {
        nodes {
          name
          attributeId
        }
      }
      variations {
        nodes {
          name
          databaseId
          price
          slug
          stockQuantity
          stockStatus
          hasAttributes
          image {
            sourceUrl
            altText
            title
          }
          attributes {
            nodes {
              value
              name
            }
          }
        }
      }
    }
  }
}
