#import "~/gql/fragments/SimpleProduct.gql"
#import "~/gql/fragments/VariableProduct.gql"

query getProducts(
  $after: String
  $slug: [String]
  $first: Int = 100
  $orderby: [ProductsOrderbyInput] = { field: DATE, order: DESC }
) {
  products(
    first: $first
    after: $after
    where: { categoryIn: $slug, typeNotIn: EXTERNAL, visibility: VISIBLE, minPrice: 0, orderby: $orderby }
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
      onSale
      slug
      type
      date
      databaseId
      id
      averageRating
      reviewCount
      terms(first: 1000) {
        nodes {
          taxonomyName
          slug
        }
      }
      productCategories {
        nodes {
          databaseId
          slug
          name
          count
        }
      }
      ...SimpleProduct
      ...VariableProduct
    }
  }
}
