fragment CategoryImage on MediaItem {
  sourceUrl(size: MEDIUM_LARGE)
  altText
  title
}
fragment ProductCategory on ProductCategory {
  count
  databaseId
  id
  name
  slug
  parentDatabaseId
  image {
    sourceUrl(size: MEDIUM_LARGE)
    altText
    title
  }
}
