fragment ExternalProduct on ExternalProduct {
  id
  databaseId
  name
  slug
  type
  price
  regularPrice
  salePrice
  externalUrl
  buttonText

  image {
    id
    sourceUrl
    altText
    title
  }

  featuredImage {
    node {
      id
      sourceUrl
      altText
      title
    }
  }

  galleryImages {
    nodes {
      id
      sourceUrl
      altText
    }
  }
}
