fragment ProductPricing on ProductWithPricing {
  price
  rawPrice: price(format: RAW)
  regularPrice
  rawRegularPrice: regularPrice(format: RAW)
  salePrice
  rawSalePrice: salePrice(format: RAW)
  onSale
}
fragment ProductStock on InventoriedProduct {
  stockStatus
  stockQuantity
  lowStockAmount
}
