fragment VariableProduct on VariableProduct {
  price
  rawPrice: price(format: RAW)
  slug
  date
  weight
  length
  width
  height
  image {
    sourceUrl
    cartSourceUrl: sourceUrl(size: THUMBNAIL)
    producCardSourceUrl: sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
    altText
    title
    databaseId
  }
  averageRating
  reviewCount
  regularPrice
  rawRegularPrice: regularPrice(format: RAW)
  salePrice
  rawSalePrice: salePrice(format: RAW)
  stockStatus
  totalSales
  stockQuantity
  lowStockAmount
  defaultAttributes {
    nodes {
      name
      attributeId
      value
      label
    }
  }
  variations(first: 100) {
    nodes {
      name
      databaseId
      price
      regularPrice
      salePrice
      slug
      stockQuantity
      stockStatus
      hasAttributes
      image {
        sourceUrl
        cartSourceUrl: sourceUrl(size: THUMBNAIL)
        producCardSourceUrl: sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
        databaseId
        altText
        title
        id
      }
      attributes {
        nodes {
          value
          name
        }
      }
    }
  }
  galleryImages {
    nodes {
      sourceUrl
      databaseId
      altText
      title
    }
  }
}
