#import "./queries/fragments/SimpleProduct.gql"
#import "./queries/fragments/VariableProduct.gql"
#import "./fragments/Terms.gql"

query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    name
    type
    databaseId
    id
    slug
    sku
    description
    rawDescription: description(format: RAW)
    shortDescription
    attributes {
      nodes {
        variation
        name
        label
        options
      }
    }
    productCategories {
      nodes {
        databaseId
        slug
        name
        count
      }
    }
    ...Terms
    ...SimpleProduct
    ...VariableProduct
    related(first: 5) {
      nodes {
        name
        slug
        ...SimpleProduct
        ...VariableProduct
      }
    }
    reviews {
      averageRating
      edges {
        rating
        node {
          content
          id
          date
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
}
