#import "./fragments/ImageFragment.gql"

mutation Checkout(
  $billing: CustomerAddressInput = {}
  $metaData: [MetaDataInput] = { key: "", value: "" }
  $paymentMethod: String = "btcpay"
  $shipping: CustomerAddressInput = {}
  $customerNote: String = ""
  $shipToDifferentAddress: Boolean = false
  $account: CreateAccountInput = { username: "", password: "" }
  $transactionId: String = ""
  $isPaid: Boolean = false
) {
  checkout(
    input: {
      paymentMethod: $paymentMethod
      billing: $billing
      metaData: $metaData
      shipping: $shipping
      customerNote: $customerNote
      shipToDifferentAddress: $shipToDifferentAddress
      account: $account
      transactionId: $transactionId
      isPaid: $isPaid
    }
  ) {
    result
    redirect
    order {
      id
      orderNumber
      orderKey
      status
      refunds {
        nodes {
          amount
        }
      }
      lineItems {
        nodes {
          product {
            node {
              id
              name
              image {
                ...ImageFragment
              }
            }
          }
          variation {
            node {
              id
              name
              image {
                ...ImageFragment
              }
            }
          }
          quantity
          total
          subtotal
        }
      }
    }
  }
}
