query getOrders {
  customer {
    orders(first: 100) {
      nodes {
        orderNumber
        total
        date
        status
        downloadableItems {
          nodes {
            name
            downloadsRemaining
            url
            product {
              name
              slug
            }
            accessExpires
          }
        }
        lineItems {
          nodes {
            product {
              node {
                name
              }
            }
          }
        }
      }
    }
  }
}
