query getOrders {
  customer {
    orders(first: 100) {
      nodes {
        orderNumber
        total
        date
        status
        lineItems {
          nodes {
            product {
              node {
                name
              }
            }
          }
        }
      }
    }
  }
}
