query GetProductBySlug($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    id
    databaseId
    name
    description
    shortDescription
    price
    regularPrice
    salePrice
    externalUrl
    buttonText
    image {
      sourceUrl
      altText
    }
    galleryImages {
      nodes {
        id
        sourceUrl
        altText
      }
    }
  }
}
