#import "./fragments/ImageFragment.gql"

query getProducts(
  $first: Int = 24
  $after: String = ""
  $where: ProductsWhereArgs = {}
) {
  products(first: $first, after: $after, where: $where) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      databaseId
      ... on SimpleProduct {
        averageRating
        slug
        description
        name
        onSale
        status
        totalSales
        reviewCount
        shortDescription
        purchasable
        catalogVisibility
        price
        regularPrice
        salePrice
        stockStatus
        stockQuantity
        image {
          ...ImageFragment
        }
        galleryImages {
          nodes {
            ...ImageFragment
          }
        }
        productCategories {
          nodes {
            id
            slug
            name
          }
        }
      }
      ... on VariableProduct {
        averageRating
        slug
        description
        name
        onSale
        status
        totalSales
        reviewCount
        shortDescription
        purchasable
        catalogVisibility
        price
        regularPrice
        stockStatus
        image {
          ...ImageFragment
        }
        galleryImages {
          nodes {
            ...ImageFragment
          }
        }
        productCategories {
          nodes {
            id
            slug
            name
          }
        }
      }
    }
  }
}
