#import "./fragments/ImageFragment.gql"

query getProduct($id: ID!) {
  product(id: $id, idType: SLUG) {
    id
    databaseId
    ... on SimpleProduct {
      averageRating
      dateOnSaleFrom
      dateOnSaleTo
      description
      name
      onSale
      purchasable
      reviewCount
      shortDescription
      slug
      status
      totalSales
      price
      regularPrice
      salePrice
      stockStatus
      stockQuantity
      image {
        ...ImageFragment
      }
      galleryImages {
        nodes {
          ...ImageFragment
        }
      }
      productCategories {
        nodes {
          id
          name
          slug
        }
      }
    }
    ... on VariableProduct {
      averageRating
      dateOnSaleFrom
      dateOnSaleTo
      description
      name
      onSale
      purchasable
      reviewCount
      shortDescription
      slug
      status
      totalSales
      price
      regularPrice
      stockStatus
      image {
        ...ImageFragment
      }
      galleryImages {
        nodes {
          ...ImageFragment
        }
      }
      productCategories {
        nodes {
          id
          name
          slug
        }
      }
      variations {
        nodes {
          id
          databaseId
          name
          price
          regularPrice
          salePrice
          stockStatus
          stockQuantity
          attributes {
            nodes {
              name
              value
            }
          }
          image {
            ...ImageFragment
          }
        }
      }
    }
  }
}
