query getRelatedProducts($category: String, $productId: ID) {
  products(
    first: 4
    where: { category: $category, exclude: [$productId] }
  ) {
    nodes {
      id
      databaseId
      name
      slug
      onSale
      price
      regularPrice
      salePrice
      stockStatus
      image {
        ...Image
      }
    }
  }
}

fragment Image on MediaItem {
  id
  sourceUrl(size: LARGE)
  altText
} 
