query getRelatedProducts($category: String, $productId: Int) {
  products(
    first: 4
    where: { category: $category, exclude: [$productId] }
  ) {
    nodes {
      id
      databaseId
      ... on SimpleProduct {
        name
        slug
        onSale
        price
        regularPrice
        salePrice
        stockStatus
        image {
          ...Image
        }
      }
      ... on VariableProduct {
        name
        slug
        onSale
        price
        regularPrice
        stockStatus
        image {
          ...Image
        }
      }
    }
  }
}

fragment Image on MediaItem {
  id
  sourceUrl(size: LARGE)
  altText
} 
