query getStripePaymentIntent($stripePaymentMethod: StripePaymentMethodEnum!, $customerId: String, $saveForFuture: Boolean) {
  stripePaymentIntent(stripePaymentMethod: $stripePaymentMethod, customerId: $customerId, saveForFuture: $saveForFuture) {
    amount
    clientSecret
    error
    id
    currency
    stripePaymentMethod
    customerSessionClientSecret
  }
}
