query getStripePaymentIntent($stripePaymentMethod: StripePaymentMethodEnum!) {
  stripePaymentIntent(stripePaymentMethod: $stripePaymentMethod) {
    amount
    clientSecret
    error
    id
    currency
  }
}
