mutation login($username: String!, $password: String!) {
  login(input: { provider: PASSWORD, credentials: { username: $username, password: $password } }) {
    authToken
    authTokenExpiration
    refreshToken
    wooSessionToken
  }
}
